### ISSUE TITLE
fix logged in/logged out states

### ISSUE THREAD

**Issue by stmcpeters** [stmcpeters/FlixFinder#12]
remove handleLogin() and consider moving isLoggedIn state around for the same logic to reduce redundancy. this will also allow you to show/hide components conditionally based on various states

**Comment by stmcpeters** [comment]
progress: 
- made sure needed props were passed from parent to child components where needed (user, setIsLoggedIn, isLoggedIn and setUser) to update states
- fixed response received on backend (`res.json` instead of `res.send`) to make sure response was being parsed correctly
- removed dependency when loading users to only load when mount, instead of every time users changes (avoid infinite loop)

need improvement:
- encountering error when logging in with existing user data: `users array is not defined` - data needs to be loaded before using `.find()`
- new user is added to the database but console receiving error: `unexpected end of JSON` - parsing issue (?)

**Comment by stmcpeters** [comment]
progress:
- still encountering error when logging in with existing user data: `users array is not defined` - data needs to be loaded before using `.find()`
```
UserAuth.jsx:49 Uncaught TypeError: Cannot read properties of undefined (reading 'find')
    at handleLoginSubmit (UserAuth.jsx:49:30)
    at HTMLUnknownElement.callCallback2 (chunk-M324AGAM.js?v=d5a15255:3672:22)
    at Object.invokeGuardedCallbackDev (chunk-M324AGAM.js?v=d5a15255:3697:24)
    at invokeGuardedCallback (chunk-M324AGAM.js?v=d5a15255:3731:39)
    at invokeGuardedCallbackAndCatchFirstError (chunk-M324AGAM.js?v=d5a15255:3734:33)
    at executeDispatch (chunk-M324AGAM.js?v=d5a15255:7012:11)
    at processDispatchQueueItemsInOrder (chunk-M324AGAM.js?v=d5a15255:7032:15)
    at processDispatchQueue (chunk-M324AGAM.js?v=d5a15255:7041:13)
    at dispatchEventsForPlugins (chunk-M324AGAM.js?v=d5a15255:7049:11)
    at chunk-M324AGAM.js?v=d5a15255:7172:20
```
UserAuth.jsx (lines 43-65)
```
  // handles login submission
  // prevents form from being submitted without validating inputs first
  const handleLoginSubmit = (event) => {
    event.preventDefault();
    if(loginData.username && loginData.password) {
      // checks if inputted loginData matches existing user data - used "usr" to limit confusion
      const userFound = user.find((usr) => usr.username === loginData.username && usr.password === loginData.password)
      // sets updates states if loginData matches existing user
      if(userFound) {
        setIsLoggedIn(true);
        setUser(userFound);
        console.log('login successful');
        // error handling if inputted loginData doesn't match an existing user
      } else {
        console.error('Login failed: ', error);
        alert('Existing user not found, please register');
      }
      // error handling if no values in login username and password
    } else {
      console.error('Both fields are required');
      alert('Please fill out both fields');
    }
  }
```
- still encountering sign up issue where the new user is added to the database but this error is logged to the console:
```
UserAuth.jsx:81 Registration error:  SyntaxError: Unexpected end of JSON input
    at UserAuth.jsx:35:29
```
UserAuth.jsx (lines 27-41)
```
 // function to handle post request to create new user
  const postUser = (newUser) => {
    return fetch("http://localhost:5001/db/users", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(newUser),
    })
        .then((response) => {
            return response.json();
        })
        .then((data) => {
            setUser(data);
            setIsLoggedIn(true);
        });
  };
```

**Comment by stmcpeters** [comment]
hey @derekhouck i've provided the full errors i was encountering and the code snippets they refer to. please let me know of any improvements i can make

**Comment by derekhouck** [comment]
> UserAuth.jsx:81 Registration error:  SyntaxError: Unexpected end of JSON input
    at UserAuth.jsx:35:29

I don't think this is coming from your front-end. I think this is saying something is wrong with the response your front-end is receiving from your server.

**Comment by derekhouck** [comment]
>     if(loginData.username && loginData.password) {
>       // checks if inputted loginData matches existing user data - used "usr" to limit confusion
>       const userFound = user.find((usr) => usr.username === loginData.username && usr.password === loginData.password)

You are asking for a `user` here when you are trying to log in as a user. I would assume at this point, `user` would be `undefined`. What you probably want here is a query to your server asking if any users with the username and password entered exist, and returning the correct user if they do.
